Switch to using percona-xtradb-cluster in debconf

diff --git a/debian/percona-xtradb-cluster-server-5.5.postrm b/debian/percona-xtradb-cluster-server-5.5.postrm
--- a/debian/percona-xtradb-cluster-server-5.5.postrm
+++ b/debian/percona-xtradb-cluster-server-5.5.postrm
@@ -19,9 +19,9 @@ MYADMIN="${PERCONA_PREFIX}/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf"
 stop_server() {
   set +e
   if [ -x /usr/sbin/invoke-rc.d ]; then
-    invoke-rc.d percona-server stop
+    invoke-rc.d percona-xtradb-cluster stop
   else
-    /etc/init.d/percona-server stop
+    /etc/init.d/percona-xtradb-cluster stop
   fi
   errno=$?
   set -e
@@ -47,7 +47,7 @@ case "$1" in
 esac
 
 #
-# - Do NOT purge logs or data if another percona-server-server* package is installed (#307473)
+# - Do NOT purge logs or data if another percona-xtradb-cluster-server* package is installed (#307473)
 # - Remove the mysql user only after all his owned files are purged.
 #   
 if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; then
@@ -55,9 +55,9 @@ if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; the
   rm -f /var/log/mysql.{log,err}{,.0,.[1234567].gz}
   rm -rf /var/log/mysql
 
-  db_input high percona-server-server-5.5/postrm_remove_databases || true
+  db_input high percona-xtradb-cluster-server-5.5/postrm_remove_databases || true
   db_go || true
-  db_get percona-server-server-5.5/postrm_remove_databases || true
+  db_get percona-xtradb-cluster-server-5.5/postrm_remove_databases || true
   if [ "$RET" = "true" ]; then
     # never remove the debian.cnf when the databases are still existing
     # else we ran into big trouble on the next install!
@@ -69,7 +69,7 @@ if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; the
 
   # (normally) Automatically added by dh_installinit
   if [ "$1" = "purge" ] ; then
-        update-rc.d percona-server remove >/dev/null || exit 0
+        update-rc.d percona-xtradb-cluster remove >/dev/null || exit 0
   fi
   # (normally) End automatically added section
 fi
@@ -81,6 +81,6 @@ if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
 fi
 # (normally) End automatically added section
 
-# no DEBHELPER here, "update-rc.d remove" fails if percona-server-server-5.5 is installed
+# no DEBHELPER here, "update-rc.d remove" fails if percona-xtradb-cluster-server-5.5 is installed
 
 exit 0
